definitions:
  handlers.AuthResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handlers.loginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
info:
  contact: {}
  description: Backend API for Flutter Chat App.
  title: Go Chat App API
  version: "1.0"
paths:
  /api/v1/auth/activate/{link}:
    get:
      consumes:
      - text/plain
      description: Activation of account after registration step
      parameters:
      - description: Generated link's end side edge
        in: path
        name: link
        required: true
        type: string
      produces:
      - text/html
      responses:
        "201":
          description: Returns the html page of success
          schema:
            type: string
        "400":
          description: 'Could not get the link from url path. Possible "error" values
            : [BAD_REQUEST]'
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "410":
          description: 'Activation link is expired . Possible "error" values : [ACTIVATION_TIME_EXPIRED]'
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: 'Server failed to process . Possible "error" values : [INTERNAL_SERVER_ERROR]'
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Activate
      tags:
      - Registration
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Basic Login operation with email and password
      parameters:
      - description: Provide your creds for creation new session on certain device
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/handlers.loginRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Session was successfully created
          schema:
            $ref: '#/definitions/handlers.AuthResponse'
        "400":
          description: 'Possible "error" values: [EMPTY_AUTH_CREDS] '
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "401":
          description: 'Possible "error" values: [INVALID_CREDS, ""]'
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: 'Server failed to process . Possible "error" values : [INTERNAL_SERVER_ERROR]'
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Login
      tags:
      - Authentication
  /api/v1/auth/logout:
    post:
      consumes:
      - text/plain
      description: Logging out by revoking session
      parameters:
      - description: '''Bearer <AccessToken>'''
        in: header
        name: AccessToken
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "204":
          description: Logged out successfully
        "401":
          description: 'Possible "error" values: [EMPTY_AUTH_CREDS]'
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: 'Server failed to process . Possible "error" values : [INTERNAL_SERVER_ERROR]'
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Log out
      tags:
      - Authorization
  /api/v1/auth/me:
    get:
      consumes:
      - text/plain
      description: Endpoint for checking authorization
      parameters:
      - description: '''Bearer <AccessToken>'''
        in: header
        name: AccessToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 'user_id": some_user_id (int)'
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: 'Possible "error" values: [INTERNAL_SERVER_ERROR]'
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Checking authorization
      tags:
      - Profile
securityDefinitions:
  CookieAuth:
    in: cookie
    name: access_token
    type: apiKey
swagger: "2.0"
